--SQL Advance Case Study
USE db_SQLCaseStudies

--Q1--BEGIN 

SELECT STATE,SUM(QUANTITY) AS CELLPHONE_BOUGHT FROM DIM_LOCATION AS A INNER JOIN FACT_TRANSACTIONS AS B 
ON A.IDLOCATION=B.IDLOCATION 
WHERE DATE>=('2005') 
GROUP BY STATE 


	
--Q1--END

--Q2--BEGIN

SELECT COUNTRY,STATE,SUM(QUANTITY) AS QTY_BOUGHT FROM DIM_LOCATION AS A INNER JOIN FACT_TRANSACTIONS AS B 
ON A.IDLOCATION=B.IDLOCATION  
LEFT JOIN DIM_MODEL AS C ON B.IDMODEL=C.IDMODEL
WHERE IDMANUFACTURER='12' AND COUNTRY='US' 
GROUP BY COUNTRY,STATE


--ARIZONA STATE OF US BOUGHT MOST 'SAMSUNG' CELLPHONES. 



--Q2--END

--Q3--BEGIN 
     
SELECT ZIPCODE, STATE,SUM(TOTALPRICE) AS TRANSACTIONS 
FROM DIM_LOCATION AS A  
RIGHT JOIN FACT_TRANSACTIONS AS B
ON A.IDLOCATION=B.IDLOCATION 
GROUP BY B.IDLOCATION, STATE,ZIPCODE








	
--Q3--END

--Q4--BEGIN

SELECT TOP 1 IDModel,Model_Name,MIN(Unit_price) AS PRICE,IDManufacturer 
FROM DIM_MODEL 
GROUP BY IDModel,Model_Name,IDManufacturer,UNIT_PRICE 
ORDER BY UNIT_PRICE

--MODEL 3210 IS CHEAPEST CELLPHONE;IDMANUFACTURER IS 14(NOKIA).






--Q4--END

--Q5--BEGIN

SELECT TOP 5 A.IDMODEL,MODEL_NAME,IDMANUFACTURER,
AVG(UNIT_PRICE) AS AVG_PRICE,
SUM(QUANTITY) AS SALES_QUANTITY 
FROM DIM_MODEL AS A  
LEFT JOIN FACT_TRANSACTIONS AS B ON A.IDMODEL=B.IDMODEL 
GROUP BY A.IDMODEL, MODEL_NAME,IDMANUFACTURER,QUANTITY,UNIT_PRICE 
ORDER BY AVG_PRICE DESC












	
--Q5--END

--Q6--BEGIN


SELECT CUSTOMER_NAME,AVG(TOTALPRICE) AS AVG_PRICE 
FROM DIM_CUSTOMER AS A  
INNER JOIN FACT_TRANSACTIONS AS B ON A.IDCUSTOMER=B.IDCUSTOMER
WHERE YEAR(DATE)='2009'   
GROUP BY CUSTOMER_NAME 
HAVING AVG(TOTALPRICE)>=500








--Q6--END
	
--Q7--BEGIN 
 
SELECT TOP 5 MODEL_NAME,SUM(QUANTITY) AS QUANTITY
FROM FACT_TRANSACTIONS AS A 
INNER JOIN DIM_MODEL AS B 
ON A.IDMODEL=B.IDMODEL 
WHERE YEAR(DATE) IN ('2008','2009','2010')
GROUP BY MODEL_NAME
ORDER BY QUANTITY DESC

	




--MODEL IPHONE 4 IS IN TOP 5 IN TERMS OF QUANTITY, SIMULTANEOUSLY IN 2008,2009 AND 2010.










--Q7--END	
--Q8--BEGIN


WITH CTE1 AS
(SELECT MANUFACTURER_NAME,SUM(TOTALPRICE)AS TOTAL_SALES,YEAR(DATE) AS YEAR,
RANK() OVER (PARTITION BY YEAR(DATE) ORDER BY SUM(TOTALPRICE) DESC)[RANK]
FROM DIM_MANUFACTURER AS A 
INNER  JOIN DIM_MODEL AS B 
ON A.IDMANUFACTURER=B.IDMANUFACTURER INNER JOIN FACT_TRANSACTIONS AS C
ON B.IDMODEL=C.IDMODEL WHERE YEAR(DATE) IN('2009','2010') 
GROUP BY MANUFACTURER_NAME,YEAR(DATE))
SELECT D.Manufacturer_Name FROM DIM_MANUFACTURER D INNER JOIN 
CTE1 ON D.Manufacturer_Name=CTE1.Manufacturer_Name
WHERE [RANK]=2



--SAMSUNG IS THE 2ND HIGHEST SELLER IN 2009.
--APPLE IS THE 2ND HIGHEST SELLER IN 2010.













--Q8--END
--Q9--BEGIN


SELECT MANUFACTURER_NAME,A.IDMANUFACTURER FROM DIM_MANUFACTURER AS A LEFT JOIN 
DIM_MODEL AS B 
ON A.IDMANUFACTURER=B.IDMANUFACTURER LEFT JOIN 
FACT_TRANSACTIONS AS C ON B.IDMODEL=C.IDMODEL
WHERE YEAR(DATE)=2010

EXCEPT

SELECT MANUFACTURER_NAME,A.IDMANUFACTURER FROM DIM_MANUFACTURER AS A LEFT JOIN 
DIM_MODEL AS B 
ON A.IDMANUFACTURER=B.IDMANUFACTURER LEFT JOIN 
FACT_TRANSACTIONS AS C ON B.IDMODEL=C.IDMODEL
WHERE YEAR(DATE)=2009





	

















--Q9--END

--Q10--BEGIN






CREATE VIEW TBL11 AS 
(SELECT  TOP 100 Customer_Name,SUM(TOTALPRICE)[PRICE],A.IDCustomer
FROM FACT_TRANSACTIONS AS A 
INNER  JOIN DIM_CUSTOMER AS B 
ON A.IDCUSTOMER=B.IDCUSTOMER
GROUP BY Customer_Name,A.IDCustomer
ORDER BY SUM(TOTALPRICE)DESC)

CREATE VIEW TBL3 AS
(SELECT CUSTOMER_NAME,AVG(TOTALPRICE) AS AVG_SPEND,AVG(QUANTITY) AS AVG_QUANTITY,
LAG(SUM(TOTALPRICE)) OVER (PARTITION BY tbl11.CUSTOMER_NAME ORDER BY YEAR(DATE)) AS PREVIOUS_SPEND
FROM FACT_TRANSACTIONS AS A INNER JOIN tbl11  ON A.IDCUSTOMER=tbl11.IDCUSTOMER
GROUP BY tbl11. CUSTOMER_NAME,year(date))

CREATE VIEW TBL5 AS
(SELECT TBL11.CUSTOMER_NAME,AVG_SPEND,PREVIOUS_SPEND,AVG_QUANTITY,
([Price]-[PREVIOUS_SPEND])*0.1/[previous_spend] AS PERCENT_OF_CHANGE
FROM TBL3 INNER JOIN TBL11 ON TBL3.CUSTOMER_NAME=TBL11.CUSTOMER_NAME)













--Q10--END





